// Generated by https://quicktype.io

export interface IComic {
  code:            number;
  status:          string;
  copyright:       string;
  attributionText: string;
  attributionHTML: string;
  etag:            string;
  data:            IComicData;
}

export interface IComicData {
  offset:  number;
  limit:   number;
  total:   number;
  count:   number;
  results: IComicResult[];
}

export interface IComicResult {
  id:                 number;
  digitalId:          number;
  title:              string;
  issueNumber:        number;
  variantDescription: string;
  description:        null | string;
  modified:           string;
  isbn:               string;
  upc:                string;
  diamondCode:        string;
  ean:                string;
  issn:               string;
  format:             string;
  pageCount:          number;
  textObjects:        IComicTextObject[];
  resourceURI:        string;
  urls:               IComicURL[];
  series:             IComicSeries;
  variants:           IComicSeries[];
  collections:        IComicSeries[];
  collectedIssues:    IComicSeries[];
  dates:              IComicDateElement[];
  prices:             IComicPrice[];
  thumbnail:          IComicThumbnail;
  images:             IComicThumbnail[];
  creators:           IComicCreators;
  characters:         IComicCharacters;
  stories:            IComicStories;
  events:             IComicCharacters;
}

export interface IComicCharacters {
  available:     number;
  collectionURI: string;
  items:         IComicSeries[];
  returned:      number;
}

export interface IComicSeries {
  resourceURI: string;
  name:        string;
}

export interface IComicCreators {
  available:     number;
  collectionURI: string;
  items:         IComicCreatorsItem[];
  returned:      number;
}

export interface IComicCreatorsItem {
  resourceURI: string;
  name:        string;
  role:        string;
}

export interface IComicDateElement {
  type: string;
  date: string;
}

export interface IComicThumbnail {
  path:      string;
  extension: string;
}

export interface IComicPrice {
  type:  string;
  price: number;
}

export interface IComicStories {
  available:     number;
  collectionURI: string;
  items:         IComicItemTypeStoriesItem[];
  returned:      number;
}

export interface IComicItemTypeStoriesItem {
  resourceURI: string;
  name:        string;
  type:        string;
}

export interface IComicTextObject {
  type:     string;
  language: string;
  text:     string;
}

export interface IComicURL {
  type: string;
  url:  string;
}
